version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
          - ./app:/var/www/app
          - ./public:/var/www/html
    depends_on:
      - mariadb
    links:
      - mariadb:mysql

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: udemy_clone_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8086:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root_password